In [3]:
import subprocess
import numpy as np
import pandas as pd
import sys
sys.path.append('../')

In [2]:
import kang

In [3]:
file_bam = '/ref/Cre/genemodel_correction/tophat/SRR2132433.tophat_out_maxintron1000.accepted_hits.bam'

**How do I codes **

Let's say 0,1,2,3,4,5,6,7,8,9 is fragment

0-1, 1-2, 2-3, 3-4 ... are linked.

each is converted into array in additive manner. 

[1,1,1,1,...] each pos is described as 'pos_inter' 



In [4]:
file_fa = '/ref/Cre/genemodel_correction/Creinhardtii_281_v5.0.fa'
dicHD2seq = kang.Fasta2dic(file_fa)

chromosome, left, right = 'chromosome_1', 1000, 20000

print ('samtools view %s %s:%d-%d > temp.sam'%(file_bam,chromosome,left,right))
subprocess.call('samtools view %s %s:%d-%d > temp.sam'%(file_bam,chromosome,left,right),shell=True)
subprocess.call('cut -f 1-20 temp.sam > temp.sam.cut',shell=True)


rows = len(dicHD2seq.keys())
columns = max([len(x) for x in dicHD2seq.values()])-1
continuity_matrix = np.zeros([rows,columns])
for line in open('temp.sam.cut'): # should be changed to zero base map
    cell         = line.strip().split('\t')
    chromosome   = int(cell[2].replace('chromosome_',''))
    startpos     = int(cell[3]) - 1 # zero based conversion 
    fragmentsize = int(cell[8])
    endpos       = startpos + fragmentsize - 1 
    startpos_inter = startpos  # startpos - nextpos 
    endpos_inter   = endpos - 1 # previouspos - endpos 
    
    continuity_matrix[chromosome,startpos_inter:fragmentsize-1] += 1  # list characteristic can utillize fragment size itself.
    
    
    

In [13]:
df_sam.head()

0    1             2    3  4     5  6    7    8  \
0   SRR2132433.1070057.2  403  chromosome_1  901  1  100M  =  750 -251   
1  SRR2132433.11181939.2  403  chromosome_1  901  0  100M  =  795 -206   
2  SRR2132433.11248243.2  403  chromosome_1  901  1  100M  =  735 -266   
3  SRR2132433.11297625.2  145  chromosome_1  908  0  100M  =  703 -305   
4  SRR2132433.19799958.1   83  chromosome_1  909  0  100M  =  832 -177   

                                                   9  ...        13      14  \
0  TCGAGAAAATAGGGGTTTGCTTCGGCACAGGGCCAAAGTTCCTGGT...  ...    XM:i:0  XO:i:0   
1  TCGAGAAAATAGGGGTTTGCTTCGGCACAGGGCCAAAGTTCCTGGT...  ...    XM:i:0  XO:i:0   
2  TCGAGAAAATAGGGGTTTGCTTCGGCACAGGGCCAAAGTTCCTGGT...  ...    XM:i:0  XO:i:0   
3  AATAGGGGTTTGCTTCGGCACAGGGCCAAAGTTCCTGGTTTGGGTC...  ...    XM:i:0  XO:i:0   
4  ATAGGGGTTTGCTTCGGCACAGGGCCAAAGTTCCTGGTTTGGGTCG...  ...    XM:i:0  XO:i:0   

       15      16        17       18      19       SRRID    READID PAIRID  
0  XG:i:0  NM:i:0  MD:Z:100  YT:Z:UU  NH:i:4  SRR2132433   1070057      2  
1  XG:i:0  NM:i:0  MD:Z:100  YT:Z:UU  NH:i:5  SRR2132433  11181939      2  
2  XG:i:0  NM:i:0  MD:Z:100  YT:Z:UU  NH:i:4  SRR2132433  11248243      2  
3  XG:i:0  NM:i:0  MD:Z:100  YT:Z:UU  NH:i:6  SRR2132433  11297625      2  
4  XG:i:0  NM:i:0  MD:Z:100  YT:Z:UU  NH:i:5  SRR2132433  19799958      1  

[5 rows x 23 columns]

In [22]:
a = np.zeros(5)

In [23]:
a

array([ 0.,  0.,  0.,  0.,  0.])

In [24]:
a[0:4] += 1

In [25]:
a

array([ 1.,  1.,  1.,  1.,  0.])

In [5]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])